### ISSUE TITLE
Package in Mason

### ISSUE THREAD

**Issue by springmeyer** [mapbox/spatial-algorithms#12]
Creating a ticket to capture two tasks:

 - [x] @springmeyer package a dev release in mason of current HEAD (as a header-only library, nothing compiled) in mason for easy testing downstream
 - [x] @artemp package an official tagged release in mason once https://github.com/mapbox/spatial-algorithms/milestone/1 is done and ready.

/cc @mapsam

**Comment by springmeyer** [comment]
Dev release being packaged as part of https://github.com/mapbox/mason/pull/486

**Comment by mapsam** [comment]
Hey @artemp - are you all set for a release? Anything I can do to help?

**Comment by mapsam** [comment]
Sounds good @artemp - I think first we need a tag on GitHub, would you mind doing that? Presume we can go from current master but I'm not sure if the plan is actually 1.x or if we want to stick to 0.1.x for the time being

**Comment by springmeyer** [comment]
👍  to tagging a v0.1.0 since this project is new and may change rapidly.

**Comment by mapsam** [comment]
queued up https://github.com/mapbox/mason/pull/540

**Comment by mapsam** [comment]
Released! https://github.com/mapbox/mason/tree/master/scripts/spatial-algorithms/0.1.0
