### ISSUE TITLE
test coverage for multigeometries in closest_point

### ISSUE THREAD

**Issue by springmeyer** [mapbox/spatial-algorithms#16]
I noticed that the closest point unit tests are lacking coverage for multipolygons and multilinestrings (https://github.com/mapbox/spatial-algorithms/blob/master/test/unit/closest_point/test-closest-point.cpp)

**Comment by artemp** [comment]
missing muti* geometries test added in ee6fe85

**Comment by springmeyer** [comment]
Thanks @artemp - questions: does winding order impact the results in this case? What winding order are we assuming? Do we need to provide `mapbox::geometry::algorithms::correct`?

**Comment by artemp** [comment]
@springmeyer - algorithms used shouldn't behave differently depending on winding order but let me verify and get back.

**Comment by artemp** [comment]
I tested `point-in-polygon` which is part of `within` algorithm using all permutations of CW/ CCW on polygon with one hole and, behaviour is correct in all cases.  Actual calculation of closest distance shouldn't be affected by order either. So my take all polygons should work correctly as far as they don't have self-intersections. 

this  is polygon I tested with
```c++

#include <iostream>
#include <list>

#include <boost/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>


int main()
{
    typedef boost::geometry::model::d2::point_xy<double> point_type;
    typedef boost::geometry::model::polygon<point_type> polygon_type;

    polygon_type poly;
    boost::geometry::read_wkt(
        "POLYGON((2 1.3,2.4 1.7,2.8 1.8,3.4 1.2,3.7 1.6,3.4 2,4.1 3,5.3 2.6,5.4 1.2,4.9 0.8,2.9 0.7,2 1.3)"
        "(4.0 2.0, 4.2 1.4, 4.8 1.9, 4.4 2.2, 4.0 2.0))", poly);

    //boost::geometry::read_wkt(
    //    "POLYGON((2 1.3,2.4 1.7,2.8 1.8,3.4 1.2,3.7 1.6,3.4 2,4.1 3,5.3 2.6,5.4 1.2,4.9 0.8,2.9 0.7,2 1.3)"
    //    "(4.0 2.0, 4.4 2.2, 4.8 1.9,4.2 1.4 ,4.0 2.0))", poly);

    boost::geometry::reverse(poly);
    point_type p(4.2, 1.8);
    std::cout << "Valid:" << (boost::geometry::is_valid(poly)) << std::endl;
    std::cout << "Simple:" << (boost::geometry::is_simple(poly)) << std::endl;
    std::cout << "within: " << (boost::geometry::within(p, poly) ? "yes" : "no") << std::endl;

    return 0;
}

```

**Comment by springmeyer** [comment]
Great, thanks for verifying @artemp - This triggers me to think that it would be excellent to have our docs spell out with algos are affected by order and which are not. For example, while `within` is (thankfully not) I presume that @flippmoke plans to add simplification and it will be: e.g. the results will be different depending on order.

**Comment by artemp** [comment]
@springmeyer - just to clarify, I was talking specifically point within polygon. I won't be surprised if  line_string within polygon and polygon within polygon will depend on correct (expected) winding order.

**Comment by artemp** [comment]
On a broader point, my understanding that we have `valid` geometries in VTs which implies expected winding order. Is this still stands ?
/cc @flippmoke @springmeyer

**Comment by flippmoke** [comment]
@artemp yes we should have expected winding order
