### ISSUE TITLE
Cmake with out connectivity

### ISSUE THREAD

**Issue by flippmoke** [mapbox/spatial-algorithms#7]
@artemp wanted to see if it was possible to add flags to the way that `mason_use` in cmake operated such that it could point to an external library by default. This is not critical but could be very nice at times.

**Comment by springmeyer** [comment]
I'm working on a slightly revised way to declare mason deps that will reduce the coupling of mason logic and cmake syntax. Stay tuned, will post a PR in the next few weeks when I have something to show.

**Comment by springmeyer** [comment]
WIP: https://github.com/mapbox/spatial-algorithms/pull/15

**Comment by flippmoke** [comment]
I think it might be productive to make this library use a layout similar to https://github.com/mapbox/hpp-skel. This would enable us to develop quickly between our different libraries. I feel that if we want to make this sort of interoperability possible we should frame it out in hpp-skel and then migrate it to all our libraries.

**Comment by springmeyer** [comment]
closing per https://github.com/mapbox/spatial-algorithms/pull/15#issuecomment-378996945: in short, this issue is now to be raised at hpp-skel (where we discuss best practices for repos based on hpp-skel).
