### ISSUE TITLE
Enable Debug and Warning Builds

### ISSUE THREAD

**Issue by flippmoke** [mapbox/spatial-algorithms#8]
Currently we do not implement a large number of compiler based warnings, we should add these as different options in cmake to enable different types of builds properly. This would enable better debugging.

**Comment by springmeyer** [comment]
> One of them seems to be caused by the -flto flag, I am not sure what is exactly causing this currently.

This was fixed in #10

> Currently we do not implement a large number of compiler based warnings

In progress at https://github.com/mapbox/spatial-algorithms/pull/14
