### ISSUE TITLE
C++11 or C++14

### ISSUE THREAD

**Issue by flippmoke** [mapbox/spatial-algorithms#9]
It is still not certain if we should target this library to support C++14 or only C++11, leaving this ticket open to signal that it is not yet decided and we should consider what features in C++ we are using at this point.

**Comment by springmeyer** [comment]
Realizing that we can easily support C++11 still (we don't use C++14 features), so I think we should do that and stick with C++11 support for the time being. Closing this and handling in https://github.com/mapbox/spatial-algorithms/pull/13

As far as the `gnu++` vs `c++` issue: I'd like to built back a best practice for this to https://github.com/mapbox/hpp-skel/issues/53, then downstream apps like `spatial-algorithms` can just use the best practice.
